name       : perl-term-size-perl
version    : 0.031
release    : 7
source     :
    - https://cpan.metacpan.org/authors/id/F/FE/FERREIRA/Term-Size-Perl-0.031.tar.gz : ae9a6746cb1b305ddc8f8d8ca46878552b9c1123628971e13a275183822f209e
license    : Artistic-1.0-Perl
component  : programming.perl
summary    : Term::Size::Perl - Perl extension for retrieving terminal size (Perl version)
description: |
    Term::Size::Perl is a Perl module which provides a straightforward way to get the size of the terminal (or window) on which a script is running.
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
check      : |
    %perl_build test
